var express = require('express')
var router = express.Router();

const books = [
  {id: 1,name: 'Petar pan',chapters: 6,follover: 1400,rating:4.5,picture: "https://kcjagodina.rs/wp-content/uploads/2019/01/plakat-small.jpg",descr: 'The famous boy who never grows old, Peter Pan is boastful and carefree; self-centred and oblivious; forgetful and fearless. In short, he is everything that you would expect the essence of childhood to be.'},
  {id: 2,name: 'Unbound',chapters: 6,follover: 1300,rating:4.4,picture: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1650136427i/60824343.jpg",descr: 'A New World. A Thousand Threats. Welcome to The Continent.Felixs life on Earth had become a series of dead-end jobs, ruined relationships, and rotating apartments smaller than most postage stamps. By all accounts, even his own, he was a coward. Too afraid to move forward, to take risks. Yet when given the chance to choose between risking his life or walking away from a deadly encounter, he didnt hesitate.Moments before his untimely demise, Felix was snatched from earth and thrust into a magical world known only as The Continent. Empowered by the System, he learns that he can strengthen himself through combat and dedication. To survive hell have to push himself beyond his limits, or else fall to the monsters all around him.'},
  {id: 3,name: 'The Dragon of Dreams',chapters: 6,follover: 1200,rating:4.2,picture: "https://www.royalroadcdn.com/public/covers-large/46919-the-dragon-of-dreams.jpg?time=1654228498 ",descr: 'This is the story of a college student who was reincarnated as a dragon with a near insatiable curiosity. Sparked by questioning his own reincarnation, he quickly gets lost in the world of magic and science, using a new type of energy known as mana to learn and exploit the inner workings of the world.Although not his original intention, with the combination of his intelligence and the miracles that occurred to allow his existence, he quickly found himself climbing the mountain of strength as if it were a small hill, and climb to a point that even mighty gods must yield to.'},
  {id: 4,name: 'Soul of the Warrior',chapters: 6,follover: 1100,rating:4.2,picture: 'https://www.royalroadcdn.com/public/covers-large/53219-soul-of-the-warrior.jpg?time=1658799548',descr: 'In a world where Classes, Stats, and Levels are the everyday norm, Reivyn has a secret.He was unusually aware of his surroundings from an incredibly early age, and Skills and Stats were acquired easily. He was just the son of an ordinary village family, and nothing appeared out of the ordinary on the surface. But below the surface, dreams of another life help shape his mentality and growth. Why does he have some remembrance of a past life, and what is his purpose in this new one?'},
  {id: 5,name: 'Book of The Dead',chapters: 6,follover: 1100,rating:4.2,picture: 'https://www.royalroadcdn.com/public/covers-large/54578-my-class-death-knight-is-just-barely-legal.jpg?time=1659360077',descr: 'With one touch of the stone, Tyron receives his Class and his life changes forever.In an instant his bright and promising future as the scion of two powerful Slayers is torn apart and he must make a decision.Will he allow his Class to be purged from his soul, or will he cling to it, abandon all that he knows, and rise to power?'},
  {id: 6,name: 'Petar pan',chapters: 6,follover: 1400,rating:4.5,picture: "https://kcjagodina.rs/wp-content/uploads/2019/01/plakat-small.jpg",descr: 'The famous boy who never grows old, Peter Pan is boastful and carefree; self-centred and oblivious; forgetful and fearless. In short, he is everything that you would expect the essence of childhood to be.'},
  {id: 7,name: 'Petar pan',chapters: 6,follover: 1400,rating:4.5,picture: "https://kcjagodina.rs/wp-content/uploads/2019/01/plakat-small.jpg",descr: 'The famous boy who never grows old, Peter Pan is boastful and carefree; self-centred and oblivious; forgetful and fearless. In short, he is everything that you would expect the essence of childhood to be.'},
  {id: 8,name: 'Petar pan',chapters: 6,follover: 1400,rating:4.5,picture: "https://kcjagodina.rs/wp-content/uploads/2019/01/plakat-small.jpg",descr: 'The famous boy who never grows old, Peter Pan is boastful and carefree; self-centred and oblivious; forgetful and fearless. In short, he is everything that you would expect the essence of childhood to be.'},
  {id: 9,name: 'Petar pan',chapters: 6,follover: 1400,rating:4.5,picture: "https://kcjagodina.rs/wp-content/uploads/2019/01/plakat-small.jpg",descr: 'The famous boy who never grows old, Peter Pan is boastful and carefree; self-centred and oblivious; forgetful and fearless. In short, he is everything that you would expect the essence of childhood to be.'},
  {id: 10,name: 'Petar pan',chapters: 6,follover: 1400,rating:4.5,picture: "https://kcjagodina.rs/wp-content/uploads/2019/01/plakat-small.jpg",descr: 'The famous boy who never grows old, Peter Pan is boastful and carefree; self-centred and oblivious; forgetful and fearless. In short, he is everything that you would expect the essence of childhood to be.'},
  {id: 11,name: 'Petar pan',chapters: 6,follover: 1400,rating:4.5,picture: "https://kcjagodina.rs/wp-content/uploads/2019/01/plakat-small.jpg",descr: 'The famous boy who never grows old, Peter Pan is boastful and carefree; self-centred and oblivious; forgetful and fearless. In short, he is everything that you would expect the essence of childhood to be.'},
  {id: 12,name: 'Petar pan',chapters: 6,follover: 1400,rating:4.5,picture: "https://kcjagodina.rs/wp-content/uploads/2019/01/plakat-small.jpg",descr: 'The famous boy who never grows old, Peter Pan is boastful and carefree; self-centred and oblivious; forgetful and fearless. In short, he is everything that you would expect the essence of childhood to be.'},
];

  router.get('/', (req, res) => {
  return res.status(201).json(books);
});
module.exports = router;